### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock 

### ISSUE THREAD

**Issue by ryancaicse** [jbruchon/winregfs#6]
Hi, developers, thank you for your checking. It seems the lock `Lock()` is not released correctly when` update_cache` in the function `get_path_nkofs`?

https://github.com/jbruchon/winregfs/blob/6f294985419b5cd6128ad5fae6ed60d110eea430/winregfs.c#L334-L364

Best,

**Comment by jbruchon** [comment]
Thanks for reporting this. Fixed in https://github.com/jbruchon/winregfs/commit/8f51b93902c835b7f1d447eeadc775dc25de99b9

**Comment by ryancaicse** [comment]
@jbruchon Thanks~
